import path from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const getCurrentBranch = (): string => {
  if (process.env.CI_COMMIT_REF_NAME) {
    return process.env.CI_COMMIT_REF_NAME;
  }
  try {
    return execSync("git rev-parse --abbrev-ref HEAD", {
      encoding: "utf-8",
    }).trim();
  } catch {
    return "main";
  }
};

const isDryRun = (): boolean => {
  return (
    process.argv.includes("--dry-run") ||
    process.env.DRY_RUN === "true" ||
    process.env.DRY_RUN === "1"
  );
};

const config = {
  // Location of report generated by bundler
  DEFAULT_STATS_PATH: path.join(__dirname, "../../../../reports/stats.json"),
  // Location where artifact should be saved
  DEFAULT_ARTIFACT_PATH: path.join(__dirname, "../../../../reports/"),
  // Filename of an artifact
  ARTIFACT_NAME: "component-sizes.txt",
  // Full path for GitLab artifact (relative to project root)
  ARTIFACT_PATH: "reports/component-sizes.txt",
  // Name of current branch
  CURRENT_BRANCH: getCurrentBranch(),
  // Merge request target branch, usually it's master
  DEFAULT_BRANCH: process.env.CI_DEFAULT_BRANCH || "master",
  // ID of the project
  GITLAB_PROJECT_ID: process.env.CI_PROJECT_ID || "261",
  // GitLab token
  TOKEN: process.env.GITLAB_TOKEN,
  // GitLab domain
  GITLAB_DOMAIN:
    process.env.CI_SERVER_HOST || process.env.GITLAB_DOMAIN || "gitlab.com",
  // User or organization name
  NAME_SPACE:
    process.env.CI_PROJECT_NAMESPACE || process.env.PROJECT_NAMESPACE || "example",
  // Repo name
  PROJECT:
    process.env.CI_PROJECT_NAME ||
    process.env.PROJECT_NAME ||
    "design-system",
  // Name of the job, which created an artifact
  JOB_NAME:
    process.env.CI_JOB_NAME || process.env.JOB_NAME || "component-size-report",
  // Dry run mode flag, for local testing
  DRY_RUN: isDryRun(),
};

export default config;
